services:

  auth:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped


  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    restart : unless-stopped

volumes:
  mongo_data: